# Generated by Django 5.1.6 on 2025-02-11 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20, unique=True)),
                ('status', models.CharField(choices=[('thinking', 'Думает'), ('invited', 'Приглашен')], default='thinking', max_length=10)),
                ('direction', models.CharField(choices=[('backend_python', 'Backend (Python)'), ('backend_js', 'Backend (JS)'), ('frontend', 'Frontend'), ('design', 'UI/UX Design')], max_length=20)),
            ],
        ),
    ]
