# Generated by Django 5.1.6 on 2025-02-11 18:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20, unique=True)),
                ('status', models.CharField(choices=[('thinking', 'Думает'), ('invited', 'Приглашен')], default='thinking', max_length=10)),
                ('direction', models.CharField(choices=[('backend_python', 'Backend (Python)'), ('backend_js', 'Backend (JS)'), ('frontend', 'Frontend'), ('design', 'UI/UX Design')], max_length=20)),
                ('contacted', models.CharField(choices=[('not_contacted', 'Не связались'), ('contacted', 'Связались')], default='not_contacted', max_length=15)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
