# Generated by Django 5.1.6 on 2025-02-12 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_interview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='contacted',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='registration_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='direction',
            field=models.CharField(blank=True, choices=[('backend_python', 'Backend (Python)'), ('backend_js', 'Backend (JS)'), ('frontend', 'Frontend'), ('design', 'UI/UX Design')], max_length=20, null=True),
        ),
    ]
