# Generated by Django 5.1.6 on 2025-02-12 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_userprofile_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='registration_date',
        ),
    ]
